fix: snapshots failing because of wrong mysql colum quoting
dbeatty10/dbt-mysql pull request #171
Opened 2024-04-04 17:05 UTC by outinim

resolves #

### Description

### Checklist
 - [ ] I have run this code in development and it appears to resolve the stated issue
 - [ ] This PR includes tests, or tests are not required/relevant for this PR
 - [ ] I have updated the `CHANGELOG.md` with information about my change

2024-04-04 17:30 UTC, mwallace582 requested changes
Made some comments, hopefully they're helpful. It'd would also be great if you'd be able to add a unit test for this new functionality.

2024-04-04 17:30 UTC, mwallace582 commented on dbt/include/mariadb/macros/materializations/snapshot/create_columns.sql
> +{% macro create_columns(relation, columns) %}
This macro is not necessary, as [it already exists](https://github.com/dbt-labs/dbt-core/blob/1.7.latest/core/dbt/include/global_project/macros/materializations/snapshots/helpers.sql#L5) within the base `dbt-core` SQL templates.

2024-04-04 17:30 UTC, mwallace582 commented on dbt/include/mariadb/macros/materializations/snapshot/create_columns.sql
While I don't think it's wrong to put this in a new file, I personally would just add the new create_columns macro to the existing `dbt/include/mariadb/macros/materializations/snapshot/snapshot.sql` file.

2024-04-04 17:30 UTC, mwallace582 commented on dbt/include/mariadb/macros/materializations/snapshot/create_columns.sql
> +{% macro default__create_columns(relation, columns) %}
The `default_` prefix is used in `dbt-core` as a prefix for the default implementation of a macro. Any adapter specific macros should be prefixed with their adapter name (`mariadb_` in this case). 
```suggestion
{% macro mariadb__create_columns(relation, columns) %}
```

2024-04-04 17:30 UTC, mwallace582 commented on dbt/include/mariadb/macros/materializations/snapshot/create_columns.sql
Due to the way that this repo is structured, when you add something for one adapter flavor (`mariadb`), you should add the same thing for `mysql5` and `mysql` (if applicable).

2024-04-07 21:36 UTC, outinim commented
Something like this is better ? Thanks for the reviews guys

2024-04-11 16:33 UTC, mwallace582 commented on dbt/include/mysql5/macros/materializations/snapshot/snapshot.sql
> +      {% do mysql5__create_columns(target_relation, missing_columns) %}
This change (and the others like it) is not necessary. The `create_columns()` macro will automatically call the adapter's specific macro if one exists (which it now does).

2024-04-11 16:40 UTC, mwallace582 commented
Sorry for the delay in taking a look at your changes. This is looking a lot better, and I've just got the one new comment.

It'd also be great if you'd be able to add some tests around this, although I'd be willing to merge this without them given the small scope of the changes.

2024-05-27 23:31 UTC, mwallace582 commented on dbt/include/mysql5/macros/materializations/snapshot/snapshot.sql
> +      {% do mysql5__create_columns(target_relation, missing_columns) %}
I've made this change myself so that we can get this merged.

2024-05-27 23:39 UTC, merged